### ISSUE TITLE
Running on Windows...

### ISSUE THREAD

**Issue by LarryEitel** [ksespinola/react-keystone#3]
I was able to launch app with:

`npm run webpack:watch && npm run backend:watch && npm run styles:watch`

in package scripts I hacked:

```
    "webpack:build": "set NODE_ENV=production && webpack --progress --colors -p",
    "webpack:watch": "set NODE_ENV=development && webpack -d --progress --colors --watch  
```

It launched a new browser tab opened to: `http://localhost:3030` however it never loads, just a loading spinner in tab.

I am very intrigued with your project. Any suggestions as to how I might get pass this?
Thank You :)

**Comment by kespinola** [comment]
I removed the setting of `NODE_ENV`. 

Do you mind pulling `master` and running `npm run dev` with an active mongo database? Also http://keystonejs.com provides more insight into the project.

The dev mode is almost where I want it. Im having issues watching the whole style folder in `styles:watch` task. I also want to look into minimizing server restarts from nodemon to help smooth out the webpack-dev-server.
